CREATE TABLE LOAITOUR
(
	MALOAI NCHAR(10) NOT NULL,
	TENLOAI NVARCHAR(50) NOT NULL,
	CONSTRAINT PK_LOAITOUR PRIMARY KEY(MALOAI)
)--OK
CREATE TABLE TOUR
(
	MATOUR NCHAR(10) NOT NULL,
	MALOAI NCHAR(10) NOT NULL,
	TENTOUR NVARCHAR(50) NOT NULL,
	SONGAY INT,
	SOCHO INT,
	CONSTRAINT PK_TOUR PRIMARY KEY(MATOUR),
	CONSTRAINT FK_TOUR_LOAITOUR FOREIGN KEY(MALOAI) REFERENCES LOAITOUR(MALOAI)
) --OK
CREATE TABLE DICHVU
(	
	MADICHVU NCHAR(10) NOT NULL,
	TENDICHVU NVARCHAR(50) NOT NULL,
	GIA MONEY,
	CONSTRAINT PK_DICHVU PRIMARY KEY(MADICHVU)
)--OK
CREATE TABLE DANHSACHDICHVU
(
	MADICHVU NCHAR(10) NOT NULL,
	MATOUR NCHAR(10) NOT NULL,
	SOLUONGDUNG INT,
	THANHTIEN FLOAT,
	CONSTRAINT PK_DANHSACHDICHVU PRIMARY KEY(MADICHVU,MATOUR),
	CONSTRAINT FK_DANHSACHDICHVU_TOUR FOREIGN KEY(MATOUR) REFERENCES TOUR(MATOUR),
	CONSTRAINT FK_DANHSACHDICHVU_DICHVU FOREIGN KEY(MADICHVU) REFERENCES DICHVU(MADICHVU)
)--OK
CREATE TABLE QUOCGIA
(
	MAQUOCGIA NCHAR(10) NOT NULL,
	TENQUOCGIA NVARCHAR(50),
	CONSTRAINT PK_QUOCGIA PRIMARY KEY(MAQUOCGIA)
)--OK
CREATE TABLE TINH
(
	MATINH NCHAR(10) NOT NULL,
	TENTINH NVARCHAR(50),
	CONSTRAINT PK_TINH PRIMARY KEY(MATINH)
)--OK
CREATE TABLE DIADIEMDULICH
(
	MADIADIEM NCHAR(10) NOT NULL,
	MAQUOCGIA NCHAR(10) NOT NULL,
	MATINH NCHAR(10) NOT NULL,
	TENDIADIEM NVARCHAR(50),
	CONSTRAINT PK_DIADIEMDULICH PRIMARY KEY(MADIADIEM),
	CONSTRAINT FK_DIADIEMDULICH_QUOCGIA FOREIGN KEY(MAQUOCGIA) REFERENCES QUOCGIA(MAQUOCGIA),
	CONSTRAINT FK_DIADIEMDULICH_TINH FOREIGN KEY(MATINH) REFERENCES TINH(MATINH)
)--OK
CREATE TABLE CHITIETTHAMQUAN
(
	MADIADIEM NCHAR(10) NOT NULL,
	MATOUR NCHAR(10) NOT NULL,
	GHICHU NTEXT,
	CONSTRAINT PK_CHITIETTHAMQUAN PRIMARY KEY(MADIADIEM,MATOUR),
	CONSTRAINT FK_CHITIETTHAMQUAN_DIADIEM FOREIGN KEY (MADIADIEM) REFERENCES DIADIEMDULICH(MADIADIEM),
	CONSTRAINT FK_CHITIETTHAMQUAN_TOUR FOREIGN KEY (MATOUR) REFERENCES TOUR(MATOUR)
)--OK
CREATE TABLE KHACHSAN
(
	MAKHACHSAN NCHAR(10) NOT NULL,
	MAQUOCGIA NCHAR(10) NOT NULL,
	MATINH NCHAR(10) NOT NULL,
	TENKHACHSAN NVARCHAR(50),
	CONSTRAINT PK_KHACHSAN PRIMARY KEY(MAKHACHSAN),
	CONSTRAINT FK_KHACHSAN_QUOCGIA FOREIGN KEY (MAQUOCGIA) REFERENCES QUOCGIA(MAQUOCGIA),
	CONSTRAINT FK_KHACHSAN_TINH FOREIGN KEY (MATINH) REFERENCES TINH(MATINH)
)--OK 
CREATE TABLE CHUONGTRINHTOUR
(
	MACHUONGTRINH NCHAR(10) NOT NULL,
	MATOUR NCHAR(10) NOT NULL,
	MAKHACHSAN NCHAR(10) NOT NULL,
	TENCHUONGTRINH NVARCHAR(50),
	NGAY DATETIME,
	CHITIET NTEXT,
	CONSTRAINT PK_CHUONGTRINHTOUR PRIMARY KEY(MACHUONGTRINH),
	CONSTRAINT FK_CHUONGTRINHTOUR_TOUR FOREIGN KEY (MATOUR) REFERENCES TOUR(MATOUR),
	CONSTRAINT FK_CHUONGTRINHTOUR_KHACHSAN FOREIGN KEY (MAKHACHSAN) REFERENCES KHACHSAN(MAKHACHSAN),
)--OK
CREATE TABLE LICHKHOIHANH
(
	MALICH NCHAR(10) NOT NULL,
	MATOUR NCHAR(10) NOT NULL,
	TENLICH NVARCHAR(50),
	SOCHOTRONG INT,
	CONSTRAINT PK_LICHKHOIHANH PRIMARY KEY(MALICH),
	CONSTRAINT FK_LICHKHOIHANH_TOUR FOREIGN KEY (MATOUR) REFERENCES TOUR(MATOUR)
)--OK
CREATE TABLE DANHSACHNGUOIDIKEM
(
	MADANHSACH NCHAR(10) NOT NULL,
	TEN NVARCHAR(50),
	GIOITINH NVARCHAR(3),
	NGAYSINH DATETIME,
	QUOCTICH NVARCHAR(50),
	PASSPORT NCHAR(10),
	CONSTRAINT PK_DANHSACHNGUOIDIKEM PRIMARY KEY(MADANHSACH)
)--OK
CREATE TABLE KHACHHANG
(
	MAKHACHHANG NCHAR(10) NOT NULL,
	TENKHACHHANG NVARCHAR(50),
	EMAIL VARCHAR(50),
	DIENTHOAI INT,
	NGAYSINH DATETIME,
	DIACHI NVARCHAR(100),
	CONSTRAINT PK_KHACHHANG PRIMARY KEY(MAKHACHHANG)
)--OK
CREATE TABLE LOAITHANHTOAN
(
	MALOAITT NCHAR(10) NOT NULL,
	TENLOAITT NVARCHAR(100),
	CHITIET NTEXT,
	CONSTRAINT PK_LOAITHANHTOAN PRIMARY KEY(MALOAITT)
)
CREATE TABLE TOURDAT
(
	MATOURDAT NCHAR(10) NOT NULL,
	MALICH NCHAR(10) NOT NULL,
	MADANHSACH NCHAR(10) NOT NULL,
	MAKHACHHANG NCHAR(10) NOT NULL,
	MALOAITT NCHAR(10) NOT NULL,
	DIEMDON NVARCHAR(50),
	NGAYDAT DATETIME,
	TRANGTHAI NVARCHAR(50),
	TONGTIEN FLOAT,
	CONSTRAINT PK_TOURDAT PRIMARY KEY(MATOURDAT),
	CONSTRAINT FK_TOURDAT_LICH FOREIGN KEY (MALICH) REFERENCES LICHKHOIHANH(MALICH),
	CONSTRAINT FK_TOURDAT_DANHSACHNGUOIDIKEM FOREIGN KEY (MADANHSACH) REFERENCES DANHSACHNGUOIDIKEM(MADANHSACH),
	CONSTRAINT FK_TOURDAT_KHACHHANG FOREIGN KEY (MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHHANG)
)--OK  
CREATE TABLE LOAIKHACH
(
	MALOAIKHACH NCHAR(10) NOT NULL,
	TENLOAIKHACH NVARCHAR(50),
	DOTUOI INT, 
	CONSTRAINT PK_LOAIKHACH PRIMARY KEY(MALOAIKHACH)
)--OK
CREATE TABLE GIAVE
(
	MAGIAVE NCHAR(10) NOT NULL,
	MATOUR NCHAR(10) NOT NULL,
	MALOAIKHACH NCHAR(10) NOT NULL,
	GIA FLOAT,
	CONSTRAINT PK_GIAVE PRIMARY KEY(MAGIAVE),
	CONSTRAINT FK_GIAVE_TOUR FOREIGN KEY(MATOUR) REFERENCES TOUR(MATOUR),
	CONSTRAINT FK_GIAVE_LOAIKHACH FOREIGN KEY(MALOAIKHACH) REFERENCES LOAIKHACH(MALOAIKHACH)
)--OK
CREATE TABLE CHITIETGIAVE
(
	MALOAIKHACH NCHAR(10) NOT NULL,
	MATOURDAT NCHAR(10),
	SOLUONGDUNG INT,
	THANHTIEN FLOAT,
	CONSTRAINT PK_CHITIETGIAVE PRIMARY KEY(MALOAIKHACH,MATOURDAT),
	CONSTRAINT FK_CHITIETGIAVE_TOURDAT FOREIGN KEY(MATOURDAT) REFERENCES TOURDAT(MATOURDAT),
	CONSTRAINT FK_CHITIETGIAVE_LOAIKHACH FOREIGN KEY(MALOAIKHACH) REFERENCES LOAIKHACH(MALOAIKHACH),
)--OK