<?xml version="1.0" encoding="utf-8"?><Database Name="Travel" Class="DataQLNguoiDungDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-BGAMJEE;Initial Catalog=Travel;User ID=sa" SettingsObjectName="DAL_QuanLiTour.Properties.Settings" SettingsPropertyName="TravelConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.QL_NguoiDung" Member="QL_NguoiDungs">
    <Type Name="QL_NguoiDung">
      <Column Name="TenDangNhap" Type="System.String" DbType="NChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ho" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="NamSinh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="Luong" Type="System.Decimal" DbType="Money" CanBeNull="true" />
    </Type>
  </Table>
</Database>